@address = http://localhost:8080/api

### Get chores
GET {{address}}/

### Create chore
POST {{address}}/
Content-Type: application/json

{
    "assignedTo": "Dawid",
    "title": "Müll wegbringen",
    "date": "2025-05-17",
    "repeatsInDays": 0,
    "done": false
}

### Update chore
@id = 1
PUT {{address}}/{{id}}
Content-Type: application/json

{
    "assignedTo": "Blubb",
    "title": "Müll wegbringen",
    "date": "2025-05-17",
    "repeatsInDays": 5,
    "done": false
}