@address = http://localhost:8080/api
@chores_address = {{address}}/chores/
@users_address = {{address}}/users/

### Get chores
GET {{chores_address}}

### Create chore
POST {{chores_address}}/
Content-Type: application/json

{
    "assigneeId": 1,
    "title": "Müll wegbringen",
    "plannedDate": "2025-05-17"
}

### Update chore
@id = 3152
PUT {{chores_address}}/{{id}}
Content-Type: application/json

{
    "assignedTo": "Blubb",
    "title": "Müll wegbringen",
    "date": "2025-05-17",
    "repeatsInDays": 5,
    "done": true
}

### Get users
GET {{users_address}}

### Create user
POST {{users_address}}
Content-Type: application/json

{
  "name": "Dawid"
}